# Generated by Django 3.2.3 on 2021-06-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50, unique=True)),
                ('gender', models.CharField(choices=[], max_length=20)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('goal', models.CharField(choices=[], default='MAINTAIN', max_length=8)),
                ('body_type', models.CharField(choices=[], default='MESOMORPH', max_length=10)),
                ('sleep', models.IntegerField()),
                ('time_reach_goal', models.IntegerField()),
            ],
        ),
    ]
